feat(DIST-1121): Document referrer as source
Typeform/embed pull request #362
Opened 2021-08-19 13:50 UTC by scarciofolomarco

2021-08-19 13:54 UTC, antoniofull approved these changes

2021-08-19 13:54 UTC, mrisoli approved these changes

2021-08-23 08:53 UTC, mathio requested changes
We should not populate source with referrer of the host page. I think this PR should be done in renderer repo. In renderer the referrer header has the value of page that linked to typeform (or embedded it in iframe). The "source" value should not be the full referrer URL, renderer should extract domain from it.

2021-08-23 10:09 UTC, scarciofolomarco commented
> We should not populate source with referrer of the host page. I think this PR should be done in renderer repo. In renderer the referrer header has the value of page that linked to typeform (or embedded it in iframe). The "source" value should not be the full referrer URL, renderer should extract domain from it.

that's why I wanted you to check this, gotta contact you for more details

2021-08-23 11:46 UTC, mathio commented
@scarciofolomarco I think we can close this.

2021-08-23 11:46 UTC, closed without merging