docs(DIST-1468): Update docs with custom icon
Typeform/embed pull request #443
Opened 2022-01-19 15:01 UTC by antoniofull

fix for #440

2022-01-20 12:39 UTC, mathio requested changes

2022-01-20 12:39 UTC, mathio commented on packages/embed/README.md
> +| customIcon             | string           | customize the message icon (popover, sidetab) )
The default value is not "image url" string.

2022-01-20 12:42 UTC, mathio commented
Please add dev portal docs to this repo ([see docs/configuration.md](https://github.com/Typeform/embed/blob/main/docs/configuration.md)), do not open [PRs](https://github.com/Typeform/dev-portal-content/pull/760) manually.

2022-01-21 05:54 UTC, maxprilutskiy approved these changes

2022-01-21 10:25 UTC, mathio requested changes
Can we please try to keep those 2 tables ([README](https://github.com/Typeform/embed/blob/dd4333c27ad3df37bc1880c1f6c42ae7fa5eb316/packages/embed/README.md) and [configuration docs](https://github.com/Typeform/embed/blob/dd4333c27ad3df37bc1880c1f6c42ae7fa5eb316/docs/configuration.md)) in sync? Same order of things, same text.

2022-01-21 11:04 UTC, antoniofull commented
> Can we please try to keep those 2 tables ([README](https://github.com/Typeform/embed/blob/dd4333c27ad3df37bc1880c1f6c42ae7fa5eb316/packages/embed/README.md) and [configuration docs](https://github.com/Typeform/embed/blob/dd4333c27ad3df37bc1880c1f6c42ae7fa5eb316/docs/configuration.md)) in sync? Same order of things, same text.

I don't see the order, buttonText in the configuration?

2022-01-24 10:17 UTC, mathio commented
> I don't see the order, buttonText it's not in the configuration?

Good catch, lets sync (copy-paste) those two tables. I just pushed a commit with this.

2022-01-24 10:17 UTC, antoniofull commented
Thanks @mathio feel free to re-approve and merge it when ready

2022-01-24 11:28 UTC, mathio approved these changes

2022-01-24 11:28 UTC, merged

2022-01-27 14:33 UTC, typeform-ops-gha commented
:tada: This PR is included in version @typeform/embed-v1.27.1 :tada:

The release is available on:
- [npm package (@latest dist-tag)](https://www.npmjs.com/package/@typeform/embed/v/1.27.1)
- [GitHub release](https://github.com/Typeform/embed/releases/tag/%40typeform/embed-v1.27.1)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: