React Hooks Example
Typeform/embed pull request #71
Opened 2020-08-25 15:36 UTC by captDaylight

This took me a second to work through how it works with React hooks, might save someone some time in the future.

2020-08-25 22:38 UTC, mathio requested changes
Thank you for your PR. Please see my comments to make the code runnable just by copy-pasting.

2020-08-25 22:38 UTC, mathio commented on README.md
> +
Your code says `typeformEmbed is not defined`. You need to import it.
```suggestion
import * as typeformEmbed from "@typeform/embed";

```

2020-08-25 22:38 UTC, mathio commented on README.md
> +    typeformEmbed.makeWidget(typeFormRef.current, 'https://form.typeform.com/to/MY_TYPEFORM_ID', {
`typeFormRef is not defined` - you have a typo in the variable name (uppercase F).

```suggestion
    typeformEmbed.makeWidget(typeformRef.current, 'https://form.typeform.com/to/MY_TYPEFORM_ID', {
```

2020-09-01 08:22 UTC, merged

2020-09-01 15:43 UTC, captDaylight commented
Sorry for the late reply, glad to see it make its way in!